// 전북대학교 커트라인 데이터
// 50%cut, 70%cut 모두 숫자인 항목만 (X명 이하 제외)
// 학종(큰사람) + 교과(일반학생) + 교과(지역인재1(호남권)) + 교과(지역인재2(전북권))

interface Entry {
  university: string;
  department: string;
  admissionType: "교과" | "학종";
  admissionName: string;
  quota: number;
  competitionRate: number;
  cutoff50Grade: number;
  cutoff70Grade: number;
}

const data: Entry[] = [
  // === 의약계열 ===
  // 의예과
  {
    university: "전북대학교",
    department: "의예과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 24,
    competitionRate: 16.6,
    cutoff50Grade: 1.35,
    cutoff70Grade: 1.38,
  },
  {
    university: "전북대학교",
    department: "의예과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 14,
    competitionRate: 19.3,
    cutoff50Grade: 1.32,
    cutoff70Grade: 1.35,
  },
  {
    university: "전북대학교",
    department: "의예과",
    admissionType: "교과",
    admissionName: "지역인재2(전북권)",
    quota: 56,
    competitionRate: 9.5,
    cutoff50Grade: 1.77,
    cutoff70Grade: 2.0,
  },
  // 수의예과
  {
    university: "전북대학교",
    department: "수의예과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 5,
    competitionRate: 31.2,
    cutoff50Grade: 1.36,
    cutoff70Grade: 1.54,
  },
  {
    university: "전북대학교",
    department: "수의예과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 10,
    competitionRate: 17.2,
    cutoff50Grade: 1.21,
    cutoff70Grade: 1.24,
  },
  {
    university: "전북대학교",
    department: "수의예과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 5,
    competitionRate: 22.4,
    cutoff50Grade: 1.21,
    cutoff70Grade: 1.42,
  },
  {
    university: "전북대학교",
    department: "수의예과",
    admissionType: "교과",
    admissionName: "지역인재2(전북권)",
    quota: 15,
    competitionRate: 10.3,
    cutoff50Grade: 1.52,
    cutoff70Grade: 1.57,
  },
  // 치의예과
  {
    university: "전북대학교",
    department: "치의예과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 4,
    competitionRate: 22.5,
    cutoff50Grade: 1.04,
    cutoff70Grade: 1.04,
  },
  {
    university: "전북대학교",
    department: "치의예과",
    admissionType: "교과",
    admissionName: "지역인재2(전북권)",
    quota: 18,
    competitionRate: 8.1,
    cutoff50Grade: 1.39,
    cutoff70Grade: 1.44,
  },
  // 약학과
  {
    university: "전북대학교",
    department: "약학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 4,
    competitionRate: 32.3,
    cutoff50Grade: 1.03,
    cutoff70Grade: 1.03,
  },
  {
    university: "전북대학교",
    department: "약학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 14,
    competitionRate: 18.9,
    cutoff50Grade: 1.3,
    cutoff70Grade: 1.33,
  },
  // 간호학과
  {
    university: "전북대학교",
    department: "간호학과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 7,
    competitionRate: 19.9,
    cutoff50Grade: 2.76,
    cutoff70Grade: 2.77,
  },
  {
    university: "전북대학교",
    department: "간호학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 10,
    competitionRate: 14.8,
    cutoff50Grade: 2.48,
    cutoff70Grade: 2.65,
  },
  {
    university: "전북대학교",
    department: "간호학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 7,
    competitionRate: 7.7,
    cutoff50Grade: 2.52,
    cutoff70Grade: 2.56,
  },
  {
    university: "전북대학교",
    department: "간호학과",
    admissionType: "교과",
    admissionName: "지역인재2(전북권)",
    quota: 38,
    competitionRate: 4.4,
    cutoff50Grade: 2.58,
    cutoff70Grade: 2.68,
  },
  // === 경상계열 ===
  {
    university: "전북대학교",
    department: "경상계열",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 43,
    competitionRate: 12.0,
    cutoff50Grade: 3.63,
    cutoff70Grade: 3.73,
  },
  {
    university: "전북대학교",
    department: "경상계열",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 105,
    competitionRate: 9.0,
    cutoff50Grade: 3.55,
    cutoff70Grade: 3.63,
  },
  {
    university: "전북대학교",
    department: "경상계열",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 73,
    competitionRate: 5.2,
    cutoff50Grade: 3.89,
    cutoff70Grade: 4.11,
  },
  // === 사회과학계열 ===
  {
    university: "전북대학교",
    department: "사회과학계열",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 43,
    competitionRate: 14.3,
    cutoff50Grade: 3.54,
    cutoff70Grade: 3.72,
  },
  {
    university: "전북대학교",
    department: "사회과학계열",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 64,
    competitionRate: 9.9,
    cutoff50Grade: 3.51,
    cutoff70Grade: 3.55,
  },
  {
    university: "전북대학교",
    department: "사회과학계열",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 42,
    competitionRate: 7.1,
    cutoff50Grade: 3.42,
    cutoff70Grade: 3.58,
  },
  {
    university: "전북대학교",
    department: "사회과학계열",
    admissionType: "교과",
    admissionName: "농어촌학생",
    quota: 5,
    competitionRate: 11.8,
    cutoff50Grade: 2.92,
    cutoff70Grade: 3.22,
  },
  // === 생활과학계열 ===
  {
    university: "전북대학교",
    department: "생활과학계열",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 13,
    competitionRate: 16.0,
    cutoff50Grade: 4.19,
    cutoff70Grade: 4.4,
  },
  {
    university: "전북대학교",
    department: "생활과학계열",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 40,
    competitionRate: 8.5,
    cutoff50Grade: 3.92,
    cutoff70Grade: 4.03,
  },
  {
    university: "전북대학교",
    department: "생활과학계열",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 10,
    competitionRate: 8.4,
    cutoff50Grade: 3.93,
    cutoff70Grade: 3.92,
  },
  {
    university: "전북대학교",
    department: "생활과학계열",
    admissionType: "교과",
    admissionName: "농어촌학생",
    quota: 4,
    competitionRate: 7.3,
    cutoff50Grade: 3.59,
    cutoff70Grade: 3.59,
  },
  // === 공학계열1 ===
  {
    university: "전북대학교",
    department: "공학계열1",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 104,
    competitionRate: 13.3,
    cutoff50Grade: 3.85,
    cutoff70Grade: 3.96,
  },
  {
    university: "전북대학교",
    department: "공학계열1",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 314,
    competitionRate: 6.6,
    cutoff50Grade: 3.65,
    cutoff70Grade: 3.82,
  },
  {
    university: "전북대학교",
    department: "공학계열1",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 187,
    competitionRate: 6.0,
    cutoff50Grade: 3.74,
    cutoff70Grade: 3.91,
  },
  {
    university: "전북대학교",
    department: "공학계열1",
    admissionType: "교과",
    admissionName: "농어촌학생",
    quota: 11,
    competitionRate: 9.9,
    cutoff50Grade: 3.33,
    cutoff70Grade: 3.76,
  },
  // === 공학계열1(소프트웨어공학과) ===
  {
    university: "전북대학교",
    department: "공학계열1(소프트웨어공학과)",
    admissionType: "학종",
    admissionName: "특성화고졸재직자",
    quota: 14,
    competitionRate: 1.0,
    cutoff50Grade: 3.16,
    cutoff70Grade: 2.8,
  },
  // === 공학계열1(IT융합기계전공학) ===
  {
    university: "전북대학교",
    department: "공학계열1(IT융합기계전공학)",
    admissionType: "학종",
    admissionName: "특성화고졸재직자",
    quota: 52,
    competitionRate: 0.2,
    cutoff50Grade: 1.86,
    cutoff70Grade: 1.88,
  },
  // === 공학계열2 ===
  {
    university: "전북대학교",
    department: "공학계열2",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 20,
    competitionRate: 11.4,
    cutoff50Grade: 3.24,
    cutoff70Grade: 3.9,
  },
  {
    university: "전북대학교",
    department: "공학계열2",
    admissionType: "학종",
    admissionName: "SW인재전형",
    quota: 5,
    competitionRate: 6.0,
    cutoff50Grade: 4.07,
    cutoff70Grade: 4.09,
  },
  {
    university: "전북대학교",
    department: "공학계열2",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 193,
    competitionRate: 3.6,
    cutoff50Grade: 3.7,
    cutoff70Grade: 4.06,
  },
  {
    university: "전북대학교",
    department: "공학계열2",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 72,
    competitionRate: 3.7,
    cutoff50Grade: 3.98,
    cutoff70Grade: 4.27,
  },
  {
    university: "전북대학교",
    department: "공학계열2",
    admissionType: "교과",
    admissionName: "농어촌학생",
    quota: 4,
    competitionRate: 6.3,
    cutoff50Grade: 4.08,
    cutoff70Grade: 4.08,
  },
  // === 농업생명과학계열 ===
  {
    university: "전북대학교",
    department: "농업생명과학계열",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 77,
    competitionRate: 10.6,
    cutoff50Grade: 4.25,
    cutoff70Grade: 4.43,
  },
  {
    university: "전북대학교",
    department: "농업생명과학계열",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 141,
    competitionRate: 6.3,
    cutoff50Grade: 4.14,
    cutoff70Grade: 4.28,
  },
  {
    university: "전북대학교",
    department: "농업생명과학계열",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 30,
    competitionRate: 6.2,
    cutoff50Grade: 4.35,
    cutoff70Grade: 4.35,
  },
  {
    university: "전북대학교",
    department: "농업생명과학계열",
    admissionType: "교과",
    admissionName: "농어촌학생",
    quota: 11,
    competitionRate: 9.7,
    cutoff50Grade: 3.46,
    cutoff70Grade: 3.27,
  },
  // === 생명자원융합학과 ===
  {
    university: "전북대학교",
    department: "생명자원융합학과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 10,
    competitionRate: 2.3,
    cutoff50Grade: 4.17,
    cutoff70Grade: 5.23,
  },
  {
    university: "전북대학교",
    department: "생명자원융합학과",
    admissionType: "학종",
    admissionName: "특성화고졸재직자",
    quota: 19,
    competitionRate: 0.8,
    cutoff50Grade: 2.38,
    cutoff70Grade: 2.94,
  },
  // === 스마트팜학과 ===
  {
    university: "전북대학교",
    department: "스마트팜학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 14,
    competitionRate: 4.9,
    cutoff50Grade: 3.95,
    cutoff70Grade: 4.51,
  },
  {
    university: "전북대학교",
    department: "스마트팜학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 3,
    competitionRate: 5.7,
    cutoff50Grade: 4.33,
    cutoff70Grade: null,
  },
  // === 자연과학계열1 ===
  {
    university: "전북대학교",
    department: "자연과학계열1",
    admissionType: "학종",
    admissionName: "큰사름",
    quota: 24,
    competitionRate: 11.0,
    cutoff50Grade: 3.78,
    cutoff70Grade: 4.06,
  },
  {
    university: "전북대학교",
    department: "자연과학계열1",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 70,
    competitionRate: 5.6,
    cutoff50Grade: 3.91,
    cutoff70Grade: 4.08,
  },
  {
    university: "전북대학교",
    department: "자연과학계열1",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 27,
    competitionRate: 4.3,
    cutoff50Grade: 4.07,
    cutoff70Grade: 4.23,
  },
  {
    university: "전북대학교",
    department: "자연과학계열1",
    admissionType: "교과",
    admissionName: "농어촌학생",
    quota: 3,
    competitionRate: 5.3,
    cutoff50Grade: 3.79,
    cutoff70Grade: null,
  },
  // === 자연과학계열2 ===
  {
    university: "전북대학교",
    department: "자연과학계열2",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 11,
    competitionRate: 7.2,
    cutoff50Grade: 4.3,
    cutoff70Grade: 4.52,
  },
  {
    university: "전북대학교",
    department: "자연과학계열2",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 71,
    competitionRate: 3.7,
    cutoff50Grade: 4.54,
    cutoff70Grade: 4.68,
  },
  {
    university: "전북대학교",
    department: "자연과학계열2",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 24,
    competitionRate: 4.3,
    cutoff50Grade: 4.54,
    cutoff70Grade: 4.29,
  },
  // === 환경생명자원계열 ===
  {
    university: "전북대학교",
    department: "환경생명자원계열",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 12,
    competitionRate: 9.8,
    cutoff50Grade: 4.69,
    cutoff70Grade: 4.72,
  },
  {
    university: "전북대학교",
    department: "환경생명자원계열",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 31,
    competitionRate: 5.5,
    cutoff50Grade: 4.82,
    cutoff70Grade: 5.17,
  },
  {
    university: "전북대학교",
    department: "환경생명자원계열",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 22,
    competitionRate: 4.6,
    cutoff50Grade: 5.52,
    cutoff70Grade: 5.65,
  },
  // === 국제이공학부 ===
  {
    university: "전북대학교",
    department: "국제이공학부",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 8,
    competitionRate: 5.9,
    cutoff50Grade: 4.72,
    cutoff70Grade: 4.76,
  },
  {
    university: "전북대학교",
    department: "국제이공학부",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 2,
    competitionRate: 16.0,
    cutoff50Grade: 4.82,
    cutoff70Grade: null,
  },
  {
    university: "전북대학교",
    department: "국제이공학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 50,
    competitionRate: 6.3,
    cutoff50Grade: 4.02,
    cutoff70Grade: 4.04,
  },
  // === 융합기술공학부1 ===
  {
    university: "전북대학교",
    department: "융합기술공학부1",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 49,
    competitionRate: 4.9,
    cutoff50Grade: 4.7,
    cutoff70Grade: 5.19,
  },
  {
    university: "전북대학교",
    department: "융합기술공학부1",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 9,
    competitionRate: 6.9,
    cutoff50Grade: 4.9,
    cutoff70Grade: 5.15,
  },
  // === 한옥학과 ===
  {
    university: "전북대학교",
    department: "한옥학과",
    admissionType: "학종",
    admissionName: "큰사람(도경회)",
    quota: 20,
    competitionRate: 0.9,
    cutoff50Grade: 4.69,
    cutoff70Grade: 5.63,
  },
  // === 과학교육학부 ===
  {
    university: "전북대학교",
    department: "과학교육학부",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 21,
    competitionRate: 6.6,
    cutoff50Grade: 3.52,
    cutoff70Grade: 3.84,
  },
  {
    university: "전북대학교",
    department: "과학교육학부",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 16,
    competitionRate: 9.1,
    cutoff50Grade: 3.34,
    cutoff70Grade: 3.46,
  },
  {
    university: "전북대학교",
    department: "과학교육학부",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 5,
    competitionRate: 6.0,
    cutoff50Grade: 3.74,
    cutoff70Grade: 3.76,
  },
  // === 교육학과 ===
  {
    university: "전북대학교",
    department: "교육학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 4,
    competitionRate: 8.0,
    cutoff50Grade: 4.11,
    cutoff70Grade: 4.2,
  },
  {
    university: "전북대학교",
    department: "교육학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 3,
    competitionRate: 6.7,
    cutoff50Grade: 4.02,
    cutoff70Grade: null,
  },
  // === 국어교육과 ===
  {
    university: "전북대학교",
    department: "국어교육과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 4,
    competitionRate: 13.8,
    cutoff50Grade: 2.97,
    cutoff70Grade: 2.97,
  },
  {
    university: "전북대학교",
    department: "국어교육과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 5,
    competitionRate: 18.0,
    cutoff50Grade: 2.56,
    cutoff70Grade: 2.56,
  },
  {
    university: "전북대학교",
    department: "국어교육과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 4,
    competitionRate: 15.3,
    cutoff50Grade: 3.17,
    cutoff70Grade: 3.17,
  },
  // === 독어교육과 ===
  {
    university: "전북대학교",
    department: "독어교육과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 3,
    competitionRate: 7.1,
    cutoff50Grade: 4.48,
    cutoff70Grade: null,
  },
  {
    university: "전북대학교",
    department: "독어교육과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 2,
    competitionRate: 5.5,
    cutoff50Grade: 4.75,
    cutoff70Grade: null,
  },
  // === 사회과교육부 ===
  {
    university: "전북대학교",
    department: "사회과교육부",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 15,
    competitionRate: 9.4,
    cutoff50Grade: 3.02,
    cutoff70Grade: 3.17,
  },
  {
    university: "전북대학교",
    department: "사회과교육부",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 16,
    competitionRate: 9.6,
    cutoff50Grade: 2.91,
    cutoff70Grade: 3.01,
  },
  {
    university: "전북대학교",
    department: "사회과교육부",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 4,
    competitionRate: 8.3,
    cutoff50Grade: 3.26,
    cutoff70Grade: 3.26,
  },
  // === 수학교육과 ===
  {
    university: "전북대학교",
    department: "수학교육과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 7,
    competitionRate: 10.3,
    cutoff50Grade: 3.77,
    cutoff70Grade: 4.12,
  },
  {
    university: "전북대학교",
    department: "수학교육과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 4,
    competitionRate: 7.3,
    cutoff50Grade: 3.1,
    cutoff70Grade: 3.1,
  },
  // === 영어교육과 ===
  {
    university: "전북대학교",
    department: "영어교육과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 4,
    competitionRate: 7.3,
    cutoff50Grade: 3.09,
    cutoff70Grade: 3.09,
  },
  {
    university: "전북대학교",
    department: "영어교육과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 5,
    competitionRate: 6.4,
    cutoff50Grade: 3.87,
    cutoff70Grade: 3.87,
  },
  {
    university: "전북대학교",
    department: "영어교육과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 4,
    competitionRate: 6.5,
    cutoff50Grade: 3.31,
    cutoff70Grade: 3.31,
  },
  // === 고고문화인류학과 ===
  {
    university: "전북대학교",
    department: "고고문화인류학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 11,
    competitionRate: 5.8,
    cutoff50Grade: 4.05,
    cutoff70Grade: 4.06,
  },
  // === 국어국문학과 ===
  {
    university: "전북대학교",
    department: "국어국문학과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 3,
    competitionRate: 16.3,
    cutoff50Grade: 3.83,
    cutoff70Grade: null,
  },
  {
    university: "전북대학교",
    department: "국어국문학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 11,
    competitionRate: 5.5,
    cutoff50Grade: 3.76,
    cutoff70Grade: 3.91,
  },
  {
    university: "전북대학교",
    department: "국어국문학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 7,
    competitionRate: 5.4,
    cutoff50Grade: 3.78,
    cutoff70Grade: 3.92,
  },
  // === 국제학부 ===
  {
    university: "전북대학교",
    department: "국제학부",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 18,
    competitionRate: 7.4,
    cutoff50Grade: 4.27,
    cutoff70Grade: 4.29,
  },
  // === 독일학과 ===
  {
    university: "전북대학교",
    department: "독일학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 11,
    competitionRate: 7.4,
    cutoff50Grade: 4.01,
    cutoff70Grade: 4.02,
  },
  {
    university: "전북대학교",
    department: "독일학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 6,
    competitionRate: 7.4,
    cutoff50Grade: 4.43,
    cutoff70Grade: 4.55,
  },
  // === 문헌정보학과 ===
  {
    university: "전북대학교",
    department: "문헌정보학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 13,
    competitionRate: 7.2,
    cutoff50Grade: 3.31,
    cutoff70Grade: 3.55,
  },
  {
    university: "전북대학교",
    department: "문헌정보학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 6,
    competitionRate: 5.3,
    cutoff50Grade: 4.28,
    cutoff70Grade: 4.33,
  },
  // === 사학과 ===
  {
    university: "전북대학교",
    department: "사학과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 4,
    competitionRate: 12.8,
    cutoff50Grade: 3.94,
    cutoff70Grade: 3.94,
  },
  {
    university: "전북대학교",
    department: "사학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 14,
    competitionRate: 5.7,
    cutoff50Grade: 3.72,
    cutoff70Grade: 3.81,
  },
  {
    university: "전북대학교",
    department: "사학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 10,
    competitionRate: 4.7,
    cutoff50Grade: 3.92,
    cutoff70Grade: 4.02,
  },
  // === 스페인·중남미학과 ===
  {
    university: "전북대학교",
    department: "스페인·중남미학과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 4,
    competitionRate: 15.3,
    cutoff50Grade: 4.19,
    cutoff70Grade: 4.19,
  },
  {
    university: "전북대학교",
    department: "스페인·중남미학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 9,
    competitionRate: 6.6,
    cutoff50Grade: 3.76,
    cutoff70Grade: 4.03,
  },
  {
    university: "전북대학교",
    department: "스페인·중남미학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 8,
    competitionRate: 6.8,
    cutoff50Grade: 3.9,
    cutoff70Grade: 3.85,
  },
  // === 영어영문학과 ===
  {
    university: "전북대학교",
    department: "영어영문학과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 7,
    competitionRate: 8.6,
    cutoff50Grade: 3.91,
    cutoff70Grade: 3.99,
  },
  {
    university: "전북대학교",
    department: "영어영문학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 14,
    competitionRate: 6.1,
    cutoff50Grade: 3.72,
    cutoff70Grade: 3.84,
  },
  {
    university: "전북대학교",
    department: "영어영문학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 9,
    competitionRate: 5.3,
    cutoff50Grade: 4.05,
    cutoff70Grade: 4.23,
  },
  // === 일본학과 ===
  {
    university: "전북대학교",
    department: "일본학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 14,
    competitionRate: 7.3,
    cutoff50Grade: 3.88,
    cutoff70Grade: 3.99,
  },
  // === 중어중문학과 ===
  {
    university: "전북대학교",
    department: "중어중문학과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 7,
    competitionRate: 12.9,
    cutoff50Grade: 4.14,
    cutoff70Grade: 4.19,
  },
  {
    university: "전북대학교",
    department: "중어중문학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 12,
    competitionRate: 6.8,
    cutoff50Grade: 4.17,
    cutoff70Grade: 4.14,
  },
  {
    university: "전북대학교",
    department: "중어중문학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 9,
    competitionRate: 5.4,
    cutoff50Grade: 4.35,
    cutoff70Grade: 4.52,
  },
  // === 철학과 ===
  {
    university: "전북대학교",
    department: "철학과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 4,
    competitionRate: 12.5,
    cutoff50Grade: 4.27,
    cutoff70Grade: 4.27,
  },
  {
    university: "전북대학교",
    department: "철학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 10,
    competitionRate: 7.6,
    cutoff50Grade: 4.07,
    cutoff70Grade: 4.28,
  },
  {
    university: "전북대학교",
    department: "철학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 7,
    competitionRate: 6.6,
    cutoff50Grade: 4.26,
    cutoff70Grade: 4.0,
  },
  // === 프랑스·아프리카학과 ===
  {
    university: "전북대학교",
    department: "프랑스·아프리카학과",
    admissionType: "학종",
    admissionName: "큰사람",
    quota: 6,
    competitionRate: 12.2,
    cutoff50Grade: 4.5,
    cutoff70Grade: 4.53,
  },
  {
    university: "전북대학교",
    department: "프랑스·아프리카학과",
    admissionType: "교과",
    admissionName: "일반학생",
    quota: 11,
    competitionRate: 7.4,
    cutoff50Grade: 4.06,
    cutoff70Grade: 4.02,
  },
  {
    university: "전북대학교",
    department: "프랑스·아프리카학과",
    admissionType: "교과",
    admissionName: "지역인재1(호남권)",
    quota: 6,
    competitionRate: 5.7,
    cutoff50Grade: 4.52,
    cutoff70Grade: 4.55,
  },
];

// null 제거
const filtered = data.filter((d) => d.cutoff70Grade !== null) as Entry[];

for (const d of filtered) {
  console.log(`  {`);
  console.log(`    university: "${d.university}",`);
  console.log(`    department: "${d.department}",`);
  console.log(`    admissionType: "${d.admissionType}",`);
  console.log(`    admissionName: "${d.admissionName}",`);
  console.log(`    quota: ${d.quota},`);
  console.log(`    competitionRate: ${d.competitionRate},`);
  console.log(`    cutoff50Grade: ${d.cutoff50Grade},`);
  console.log(`    cutoff70Grade: ${d.cutoff70Grade},`);
  console.log(`  },`);
}
console.log(`Total: ${filtered.length}`);
