// 조선대학교 커트라인 데이터 - 학종 + 교과(일반전형)
// 이미지에서 파싱, "3명이하" 항목 제외

interface Entry {
  university: string;
  department: string;
  admissionType: "교과" | "학종";
  admissionName: string;
  quota: number;
  competitionRate: number;
  cutoff50Grade: number;
  cutoff70Grade: number;
}

const data: Entry[] = [
  // 의예과
  {
    university: "조선대학교",
    department: "의예과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 10,
    competitionRate: 11.6,
    cutoff50Grade: 1.23,
    cutoff70Grade: 1.48,
  },
  {
    university: "조선대학교",
    department: "의예과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 16,
    competitionRate: 15.5,
    cutoff50Grade: 1.09,
    cutoff70Grade: 1.1,
  },
  // 치의예과
  {
    university: "조선대학교",
    department: "치의예과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 16.33,
    cutoff50Grade: 1.45,
    cutoff70Grade: 1.45,
  },
  {
    university: "조선대학교",
    department: "치의예과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 13,
    competitionRate: 20.69,
    cutoff50Grade: 1.16,
    cutoff70Grade: 1.17,
  },
  // 약학과
  {
    university: "조선대학교",
    department: "약학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 27.33,
    cutoff50Grade: 1.53,
    cutoff70Grade: 1.59,
  },
  {
    university: "조선대학교",
    department: "약학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 21,
    competitionRate: 24.43,
    cutoff50Grade: 1.24,
    cutoff70Grade: 1.25,
  },
  // 간호학과
  {
    university: "조선대학교",
    department: "간호학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 23,
    cutoff50Grade: 2.83,
    cutoff70Grade: 3.03,
  },
  {
    university: "조선대학교",
    department: "간호학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 5,
    competitionRate: 21.2,
    cutoff50Grade: 2.38,
    cutoff70Grade: 2.73,
  },
  {
    university: "조선대학교",
    department: "간호학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 13,
    competitionRate: 11.08,
    cutoff50Grade: 2.91,
    cutoff70Grade: 3.05,
  },
  // AI소프트웨어학부(데이터사이언스(DS)전공)
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(데이터사이언스전공)",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 1.7,
    cutoff50Grade: 6.27,
    cutoff70Grade: 7.89,
  },
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(데이터사이언스전공)",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 4,
    competitionRate: 5.5,
    cutoff50Grade: 5.71,
    cutoff70Grade: 5.71,
  },
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(데이터사이언스전공)",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 3.14,
    cutoff50Grade: 5.76,
    cutoff70Grade: 6.57,
  },
  // AI소프트웨어학부(인공지능공학전공)
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(인공지능공학전공)",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 21,
    competitionRate: 3.29,
    cutoff50Grade: 5.13,
    cutoff70Grade: 5.48,
  },
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(인공지능공학전공)",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 29,
    competitionRate: 3.31,
    cutoff50Grade: 5.18,
    cutoff70Grade: 5.6,
  },
  // AI소프트웨어학부(소프트웨어전공)
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(소프트웨어전공)",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 13,
    competitionRate: 2.69,
    cutoff50Grade: 5.83,
    cutoff70Grade: 3.5,
  },
  // AI소프트웨어학부(정보보안전공)
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(정보보안전공)",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 4,
    competitionRate: 7.5,
    cutoff50Grade: 5.37,
    cutoff70Grade: 5.37,
  },
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(정보보안전공)",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 13,
    competitionRate: 3.23,
    cutoff50Grade: 5.19,
    cutoff70Grade: 5.3,
  },
  // AI소프트웨어학부(전자전공)
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(전자전공)",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 24,
    competitionRate: 1.96,
    cutoff50Grade: 6.43,
    cutoff70Grade: 6.44,
  },
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(전자전공)",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 36,
    competitionRate: 3.97,
    cutoff50Grade: 6.17,
    cutoff70Grade: 6.14,
  },
  // AI소프트웨어학부(산업공학전공) — Image 26
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(산업공학전공)",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 44,
    competitionRate: 3.23,
    cutoff50Grade: 4.6,
    cutoff70Grade: 3.85,
  },
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(산업공학전공)",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 10,
    competitionRate: 8.5,
    cutoff50Grade: 4.03,
    cutoff70Grade: 4.63,
  },
  {
    university: "조선대학교",
    department: "AI소프트웨어학부(산업공학전공)",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 47,
    competitionRate: 3.72,
    cutoff50Grade: 4.62,
    cutoff70Grade: 5.16,
  },
  // K-컬처공연·기획학과
  {
    university: "조선대학교",
    department: "K-컬처공연·기획학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 8,
    competitionRate: 5.88,
    cutoff50Grade: 5.13,
    cutoff70Grade: 5.02,
  },
  {
    university: "조선대학교",
    department: "K-컬처공연·기획학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 10,
    competitionRate: 4.9,
    cutoff50Grade: 5.84,
    cutoff70Grade: 5.24,
  },
  {
    university: "조선대학교",
    department: "K-컬처공연·기획학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 6.5,
    cutoff50Grade: 5.02,
    cutoff70Grade: 4.73,
  },
  // 건축공학과
  {
    university: "조선대학교",
    department: "건축공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 11,
    competitionRate: 9.09,
    cutoff50Grade: 4.78,
    cutoff70Grade: 4.64,
  },
  {
    university: "조선대학교",
    department: "건축공학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 10,
    competitionRate: 7.6,
    cutoff50Grade: 5.6,
    cutoff70Grade: 5.52,
  },
  {
    university: "조선대학교",
    department: "건축공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 26,
    competitionRate: 3.88,
    cutoff50Grade: 4.67,
    cutoff70Grade: 4.51,
  },
  // 경영학부 — Image 27
  {
    university: "조선대학교",
    department: "경영학부",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 50,
    competitionRate: 3.44,
    cutoff50Grade: 5.21,
    cutoff70Grade: 5.46,
  },
  {
    university: "조선대학교",
    department: "경영학부",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 13.33,
    cutoff50Grade: 4.54,
    cutoff70Grade: 4.87,
  },
  {
    university: "조선대학교",
    department: "경영학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 135,
    competitionRate: 4.02,
    cutoff50Grade: 4.8,
    cutoff70Grade: 4.71,
  },
  // 경제학과
  {
    university: "조선대학교",
    department: "경제학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 43,
    competitionRate: 2.58,
    cutoff50Grade: 6.05,
    cutoff70Grade: 6.35,
  },
  {
    university: "조선대학교",
    department: "경제학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 12.33,
    cutoff50Grade: 4.78,
    cutoff70Grade: 5.68,
  },
  {
    university: "조선대학교",
    department: "경제학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 60,
    competitionRate: 3.32,
    cutoff50Grade: 5.89,
    cutoff70Grade: 5.99,
  },
  // 경찰행정학과
  {
    university: "조선대학교",
    department: "경찰행정학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 6,
    competitionRate: 7.13,
    cutoff50Grade: 3.83,
    cutoff70Grade: 3.97,
  },
  {
    university: "조선대학교",
    department: "경찰행정학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 11.83,
    cutoff50Grade: 3.82,
    cutoff70Grade: 4.39,
  },
  {
    university: "조선대학교",
    department: "경찰행정학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 16,
    competitionRate: 9.44,
    cutoff50Grade: 3.42,
    cutoff70Grade: 2.69,
  },
  // 공공인권법무학과
  {
    university: "조선대학교",
    department: "공공인권법무학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 9,
    competitionRate: 3.29,
    cutoff50Grade: 6.13,
    cutoff70Grade: 5.95,
  },
  {
    university: "조선대학교",
    department: "공공인권법무학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 15,
    competitionRate: 4.33,
    cutoff50Grade: 5.34,
    cutoff70Grade: 5.38,
  },
  // 공기술공학과 — Image 28
  {
    university: "조선대학교",
    department: "공기술공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 5,
    competitionRate: 1.92,
    cutoff50Grade: 7.67,
    cutoff70Grade: 7.87,
  },
  {
    university: "조선대학교",
    department: "공기술공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 5,
    cutoff50Grade: 6.86,
    cutoff70Grade: 6.86,
  },
  // 교육학과
  {
    university: "조선대학교",
    department: "교육학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 6,
    competitionRate: 2.83,
    cutoff50Grade: 4.67,
    cutoff70Grade: 4.96,
  },
  {
    university: "조선대학교",
    department: "교육학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 12,
    competitionRate: 3.75,
    cutoff50Grade: 4.17,
    cutoff70Grade: 4.36,
  },
  // 국어교육과
  {
    university: "조선대학교",
    department: "국어교육과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 11,
    competitionRate: 3.55,
    cutoff50Grade: 4.66,
    cutoff70Grade: 4.46,
  },
  {
    university: "조선대학교",
    department: "국어교육과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 4,
    competitionRate: 5.75,
    cutoff50Grade: 3.92,
    cutoff70Grade: 3.92,
  },
  {
    university: "조선대학교",
    department: "국어교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 20,
    competitionRate: 4.8,
    cutoff50Grade: 4.24,
    cutoff70Grade: 4.42,
  },
  // 국어국문학전공
  {
    university: "조선대학교",
    department: "국어국문학전공",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 16,
    competitionRate: 2.75,
    cutoff50Grade: 6.18,
    cutoff70Grade: 6.67,
  },
  {
    university: "조선대학교",
    department: "국어국문학전공",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 17,
    competitionRate: 6.21,
    cutoff50Grade: 5.54,
    cutoff70Grade: 5.69,
  },
  // 글로벌비즈니스커뮤니케이션학과 — Image 29
  {
    university: "조선대학교",
    department: "글로벌비즈니스커뮤니케이션학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 5,
    competitionRate: 3.2,
    cutoff50Grade: 5.62,
    cutoff70Grade: 5.69,
  },
  {
    university: "조선대학교",
    department: "글로벌비즈니스커뮤니케이션학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 9.5,
    cutoff50Grade: 5.62,
    cutoff70Grade: 5.8,
  },
  {
    university: "조선대학교",
    department: "글로벌비즈니스커뮤니케이션학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 4.6,
    cutoff50Grade: 5.45,
    cutoff70Grade: 5.01,
  },
  // 기계공학과
  {
    university: "조선대학교",
    department: "기계공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 56,
    competitionRate: 2.23,
    cutoff50Grade: 6.17,
    cutoff70Grade: 6.23,
  },
  {
    university: "조선대학교",
    department: "기계공학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 13.5,
    cutoff50Grade: 5.3,
    cutoff70Grade: 5.02,
  },
  {
    university: "조선대학교",
    department: "기계공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 112,
    competitionRate: 4.11,
    cutoff50Grade: 5.29,
    cutoff70Grade: 5.71,
  },
  // 독일어문학전공
  {
    university: "조선대학교",
    department: "독일어문학전공",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 9,
    competitionRate: 2,
    cutoff50Grade: 6.59,
    cutoff70Grade: 6.9,
  },
  // 디자인공학과
  {
    university: "조선대학교",
    department: "디자인공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 8,
    competitionRate: 2.33,
    cutoff50Grade: 6.59,
    cutoff70Grade: 6.9,
  },
  // 라이프스타일디자인학부(산업디자인전공+의류패션디자인전공)
  {
    university: "조선대학교",
    department: "라이프스타일디자인학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 14,
    competitionRate: 6.14,
    cutoff50Grade: 4.63,
    cutoff70Grade: 5.05,
  },
  // 러시아어전공 — Image 30
  {
    university: "조선대학교",
    department: "러시아어전공",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 7,
    competitionRate: 1.57,
    cutoff50Grade: 7.2,
    cutoff70Grade: 7.2,
  },
  // 만화·애니메이션학과
  {
    university: "조선대학교",
    department: "만화·애니메이션학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 4,
    competitionRate: 8.13,
    cutoff50Grade: 5.86,
    cutoff70Grade: 5.32,
  },
  // 무역학과
  {
    university: "조선대학교",
    department: "무역학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 33,
    competitionRate: 2.91,
    cutoff50Grade: 6.29,
    cutoff70Grade: 6.96,
  },
  {
    university: "조선대학교",
    department: "무역학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 6.67,
    cutoff50Grade: 5.81,
    cutoff70Grade: 5.81,
  },
  {
    university: "조선대학교",
    department: "무역학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 39,
    competitionRate: 2.77,
    cutoff50Grade: 5.86,
    cutoff70Grade: 6.68,
  },
  // 문예창작학과
  {
    university: "조선대학교",
    department: "문예창작학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 4,
    competitionRate: 7.17,
    cutoff50Grade: 5.01,
    cutoff70Grade: 5.35,
  },
  {
    university: "조선대학교",
    department: "문예창작학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 4,
    competitionRate: 6,
    cutoff50Grade: 5.19,
    cutoff70Grade: 5.19,
  },
  // 문화관광조경학부(시각생태조경디자인학전공) — reading from image
  {
    university: "조선대학교",
    department: "문화관광조경학부(시각생태조경디자인학전공)",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 12,
    competitionRate: 2.42,
    cutoff50Grade: 6.78,
    cutoff70Grade: 8.19,
  },
  // 문화관광학부(대중문화학(디자이너·구조·기능 디자인전공))
  {
    university: "조선대학교",
    department: "문화관광학부(대중문화학전공)",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 7,
    competitionRate: 6.71,
    cutoff50Grade: 4.96,
    cutoff70Grade: 4.7,
  },
  // 물리교육과 — Image 30 continued
  {
    university: "조선대학교",
    department: "물리교육과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 1.6,
    cutoff50Grade: 4.89,
    cutoff70Grade: 7.23,
  },
  {
    university: "조선대학교",
    department: "물리교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 2.4,
    cutoff50Grade: 4.29,
    cutoff70Grade: 4.29,
  },
  // 미디어커뮤니케이션학과 — Image 31
  {
    university: "조선대학교",
    department: "미디어커뮤니케이션학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 10.7,
    cutoff50Grade: 4.71,
    cutoff70Grade: 4.74,
  },
  {
    university: "조선대학교",
    department: "미디어커뮤니케이션학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 13.33,
    cutoff50Grade: 4.8,
    cutoff70Grade: 5.23,
  },
  {
    university: "조선대학교",
    department: "미디어커뮤니케이션학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 23,
    competitionRate: 5.96,
    cutoff50Grade: 4.13,
    cutoff70Grade: 4.33,
  },
  // 반도체학과
  {
    university: "조선대학교",
    department: "반도체학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 1.5,
    cutoff50Grade: 5.84,
    cutoff70Grade: 2.7,
  },
  {
    university: "조선대학교",
    department: "반도체학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 2.83,
    cutoff50Grade: 6.52,
    cutoff70Grade: 5.04,
  },
  // 법학과
  {
    university: "조선대학교",
    department: "법학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 22,
    competitionRate: 2.91,
    cutoff50Grade: 4.98,
    cutoff70Grade: 4.95,
  },
  {
    university: "조선대학교",
    department: "법학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 10,
    competitionRate: 5.7,
    cutoff50Grade: 5.12,
    cutoff70Grade: 5.89,
  },
  {
    university: "조선대학교",
    department: "법학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 40,
    competitionRate: 3.23,
    cutoff50Grade: 5.02,
    cutoff70Grade: 5.44,
  },
  // 산업공학과 — Image 31
  {
    university: "조선대학교",
    department: "산업공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 14,
    competitionRate: 1.93,
    cutoff50Grade: 6.55,
    cutoff70Grade: 7.64,
  },
  {
    university: "조선대학교",
    department: "산업공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 7.29,
    cutoff50Grade: 6.4,
    cutoff70Grade: 6.74,
  },
  // 상담심리학과 — Image 32
  {
    university: "조선대학교",
    department: "상담심리학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 8.2,
    cutoff50Grade: 4.5,
    cutoff70Grade: 4.37,
  },
  {
    university: "조선대학교",
    department: "상담심리학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 7.67,
    cutoff50Grade: 4.63,
    cutoff70Grade: 4.4,
  },
  {
    university: "조선대학교",
    department: "상담심리학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 19,
    competitionRate: 4.47,
    cutoff50Grade: 3.96,
    cutoff70Grade: 4.38,
  },
  // 생명과학과
  {
    university: "조선대학교",
    department: "생명과학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 4.1,
    cutoff50Grade: 5.46,
    cutoff70Grade: 6.08,
  },
  {
    university: "조선대학교",
    department: "생명과학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 21,
    competitionRate: 3.71,
    cutoff50Grade: 5.07,
    cutoff70Grade: 5.51,
  },
  // 생명화학공학과
  {
    university: "조선대학교",
    department: "생명화학공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 21,
    competitionRate: 2.38,
    cutoff50Grade: 6.35,
    cutoff70Grade: 5.7,
  },
  {
    university: "조선대학교",
    department: "생명화학공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 15,
    competitionRate: 5.53,
    cutoff50Grade: 4.91,
    cutoff70Grade: 4.98,
  },
  // 생물교육과
  {
    university: "조선대학교",
    department: "생물교육과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 6,
    competitionRate: 5,
    cutoff50Grade: 3.66,
    cutoff70Grade: 5.03,
  },
  {
    university: "조선대학교",
    department: "생물교육과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 4,
    competitionRate: 5,
    cutoff50Grade: 3.43,
    cutoff70Grade: 4.3,
  },
  {
    university: "조선대학교",
    department: "생물교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 5.64,
    cutoff50Grade: 4,
    cutoff70Grade: 4.38,
  },
  // 선박해양공학과
  {
    university: "조선대학교",
    department: "선박해양공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 16,
    competitionRate: 2.56,
    cutoff50Grade: 8.21,
    cutoff70Grade: 8.48,
  },
  {
    university: "조선대학교",
    department: "선박해양공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 3.25,
    cutoff50Grade: 6.22,
    cutoff70Grade: 7.06,
  },
  // 소방재난관리학과 — Image 33
  {
    university: "조선대학교",
    department: "소방재난관리학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 8.7,
    cutoff50Grade: 5.97,
    cutoff70Grade: 4.63,
  },
  {
    university: "조선대학교",
    department: "소방재난관리학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 12.33,
    cutoff50Grade: 3.52,
    cutoff70Grade: 5.24,
  },
  {
    university: "조선대학교",
    department: "소방재난관리학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 18,
    competitionRate: 6.5,
    cutoff50Grade: 4.76,
    cutoff70Grade: 4.87,
  },
  // 수학교육과
  {
    university: "조선대학교",
    department: "수학교육과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 11,
    competitionRate: 3.64,
    cutoff50Grade: 5.62,
    cutoff70Grade: 5.08,
  },
  {
    university: "조선대학교",
    department: "수학교육과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 4,
    competitionRate: 4.5,
    cutoff50Grade: 5.06,
    cutoff70Grade: 5.06,
  },
  {
    university: "조선대학교",
    department: "수학교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 12,
    competitionRate: 4.25,
    cutoff50Grade: 4.34,
    cutoff70Grade: 4.1,
  },
  // 스페인중남미전공
  {
    university: "조선대학교",
    department: "스페인중남미전공",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 11,
    competitionRate: 2,
    cutoff50Grade: 7,
    cutoff70Grade: 7.49,
  },
  {
    university: "조선대학교",
    department: "스페인중남미전공",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 5.78,
    cutoff50Grade: 6.33,
    cutoff70Grade: 6.63,
  },
  // 스포츠산업학과
  {
    university: "조선대학교",
    department: "스포츠산업학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 12,
    competitionRate: 8.58,
    cutoff50Grade: 4.99,
    cutoff70Grade: 5.1,
  },
  {
    university: "조선대학교",
    department: "스포츠산업학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 8,
    competitionRate: 10,
    cutoff50Grade: 5.46,
    cutoff70Grade: 5.08,
  },
  {
    university: "조선대학교",
    department: "스포츠산업학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 14.71,
    cutoff50Grade: 3.54,
    cutoff70Grade: 3.54,
  },
  // 시각디자인학과
  {
    university: "조선대학교",
    department: "시각디자인학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 8.2,
    cutoff50Grade: 4.81,
    cutoff70Grade: 5.26,
  },
  {
    university: "조선대학교",
    department: "시각디자인학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 8.83,
    cutoff50Grade: 5.09,
    cutoff70Grade: 5.22,
  },
  // 식품영양학과
  {
    university: "조선대학교",
    department: "식품영양학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 9,
    competitionRate: 5.18,
    cutoff50Grade: 4.38,
    cutoff70Grade: 2.09,
  },
  {
    university: "조선대학교",
    department: "식품영양학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 23,
    competitionRate: 2.65,
    cutoff50Grade: 4.62,
    cutoff70Grade: 5.29,
  },
  // 신소재공학과 — Image 34
  {
    university: "조선대학교",
    department: "신소재공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 26,
    competitionRate: 1.88,
    cutoff50Grade: 5.94,
    cutoff70Grade: 6.87,
  },
  {
    university: "조선대학교",
    department: "신소재공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 23,
    competitionRate: 4.26,
    cutoff50Grade: 5.63,
    cutoff70Grade: 6.56,
  },
  // 아발아전공
  {
    university: "조선대학교",
    department: "아랍어전공",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 1.4,
    cutoff50Grade: 3.93,
    cutoff70Grade: 7.35,
  },
  {
    university: "조선대학교",
    department: "아랍어전공",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 4,
    competitionRate: 5.25,
    cutoff50Grade: 7.04,
    cutoff70Grade: 6.84,
  },
  // 언어치료학과
  {
    university: "조선대학교",
    department: "언어치료학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 7,
    competitionRate: 3.57,
    cutoff50Grade: 4.56,
    cutoff70Grade: 3.03,
  },
  {
    university: "조선대학교",
    department: "언어치료학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 5,
    cutoff50Grade: 4.89,
    cutoff70Grade: 5.55,
  },
  {
    university: "조선대학교",
    department: "언어치료학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 16,
    competitionRate: 3.56,
    cutoff50Grade: 4.96,
    cutoff70Grade: 5.5,
  },
  // 역사문화학과
  {
    university: "조선대학교",
    department: "역사문화학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 9,
    competitionRate: 3.11,
    cutoff50Grade: 4.86,
    cutoff70Grade: 5.89,
  },
  {
    university: "조선대학교",
    department: "역사문화학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 18,
    competitionRate: 4.39,
    cutoff50Grade: 4.94,
    cutoff70Grade: 4.82,
  },
  // 영어교육과 — Image 35
  {
    university: "조선대학교",
    department: "영어교육과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 11,
    competitionRate: 2.82,
    cutoff50Grade: 5.61,
    cutoff70Grade: 5.15,
  },
  {
    university: "조선대학교",
    department: "영어교육과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 4,
    competitionRate: 4.25,
    cutoff50Grade: 4.79,
    cutoff70Grade: 4.79,
  },
  {
    university: "조선대학교",
    department: "영어교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 20,
    competitionRate: 6.15,
    cutoff50Grade: 3.13,
    cutoff70Grade: 4.29,
  },
  // 한국어교육전공
  {
    university: "조선대학교",
    department: "한국어교육전공",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 3,
    cutoff50Grade: 7.05,
    cutoff70Grade: 7.14,
  },
  // 항공우주공학과
  {
    university: "조선대학교",
    department: "항공우주공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 1.7,
    cutoff50Grade: 6.61,
    cutoff70Grade: 6.61,
  },
  {
    university: "조선대학교",
    department: "항공우주공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 3.11,
    cutoff50Grade: 4.69,
    cutoff70Grade: 5.45,
  },
  // 행정복지학부
  {
    university: "조선대학교",
    department: "행정복지학부",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 22,
    competitionRate: 3.95,
    cutoff50Grade: 4.72,
    cutoff70Grade: 3.1,
  },
  {
    university: "조선대학교",
    department: "행정복지학부",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 4,
    competitionRate: 4.3,
    cutoff50Grade: 5.94,
    cutoff70Grade: 5.6,
  },
  {
    university: "조선대학교",
    department: "행정복지학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 25,
    competitionRate: 4.36,
    cutoff50Grade: 4.38,
    cutoff70Grade: 5,
  },
  // 화학교육과
  {
    university: "조선대학교",
    department: "화학교육과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 1.9,
    cutoff50Grade: 5.14,
    cutoff70Grade: 5.68,
  },
  {
    university: "조선대학교",
    department: "화학교육과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 1.9,
    cutoff50Grade: 5.14,
    cutoff70Grade: 5.68,
  },
  // 환경공학과
  {
    university: "조선대학교",
    department: "환경공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 20,
    competitionRate: 3.05,
    cutoff50Grade: 5.67,
    cutoff70Grade: 5.74,
  },
  {
    university: "조선대학교",
    department: "환경공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 14,
    competitionRate: 5.5,
    cutoff50Grade: 5.47,
    cutoff70Grade: 5.63,
  },
  // 전자공학과 — Image 37
  {
    university: "조선대학교",
    department: "전자공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 47,
    competitionRate: 1.68,
    cutoff50Grade: 5.72,
    cutoff70Grade: 5.93,
  },
  {
    university: "조선대학교",
    department: "전자공학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 7.83,
    cutoff50Grade: 4.92,
    cutoff70Grade: 5.47,
  },
  {
    university: "조선대학교",
    department: "전자공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 68,
    competitionRate: 2.34,
    cutoff50Grade: 5.24,
    cutoff70Grade: 5.59,
  },
  // 정치외교학과
  {
    university: "조선대학교",
    department: "정치외교학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 12,
    competitionRate: 2.33,
    cutoff50Grade: 6.57,
    cutoff70Grade: 6.61,
  },
  {
    university: "조선대학교",
    department: "정치외교학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 4,
    competitionRate: 9.75,
    cutoff50Grade: 5.43,
    cutoff70Grade: 5.43,
  },
  {
    university: "조선대학교",
    department: "정치외교학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 26,
    competitionRate: 4.31,
    cutoff50Grade: 5.78,
    cutoff70Grade: 6.21,
  },
  // 중국어문학전공
  {
    university: "조선대학교",
    department: "중국어문학전공",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 3.4,
    cutoff50Grade: 5.69,
    cutoff70Grade: 7.52,
  },
  {
    university: "조선대학교",
    department: "중국어문학전공",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 21,
    competitionRate: 3.05,
    cutoff50Grade: 6.7,
    cutoff70Grade: 6.41,
  },
  // 지구과학교육과
  {
    university: "조선대학교",
    department: "지구과학교육과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 6,
    competitionRate: 4.5,
    cutoff50Grade: 3.76,
    cutoff70Grade: 4.12,
  },
  {
    university: "조선대학교",
    department: "지구과학교육과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 4,
    competitionRate: 6.75,
    cutoff50Grade: 4.31,
    cutoff70Grade: 4.31,
  },
  {
    university: "조선대학교",
    department: "지구과학교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 6.3,
    cutoff50Grade: 4,
    cutoff70Grade: 3.92,
  },
  // 의생명학과 — Image 38
  {
    university: "조선대학교",
    department: "의생명학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 3.3,
    cutoff50Grade: 5.38,
    cutoff70Grade: 5.15,
  },
  {
    university: "조선대학교",
    department: "의생명학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 23,
    competitionRate: 2.65,
    cutoff50Grade: 4.62,
    cutoff70Grade: 5.29,
  },
  // 일본어전공
  {
    university: "조선대학교",
    department: "일본어전공",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 6.9,
    cutoff50Grade: 5.15,
    cutoff70Grade: 5.6,
  },
  {
    university: "조선대학교",
    department: "일본어전공",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 14,
    competitionRate: 6.86,
    cutoff50Grade: 4.55,
    cutoff70Grade: 5.4,
  },
  // 자유전공학부
  {
    university: "조선대학교",
    department: "자유전공학부",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 32,
    competitionRate: 5.97,
    cutoff50Grade: 5.32,
    cutoff70Grade: 5.24,
  },
  {
    university: "조선대학교",
    department: "자유전공학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 30,
    competitionRate: 6.73,
    cutoff50Grade: 4.86,
    cutoff70Grade: 3.4,
  },
  // 직업치료학과
  {
    university: "조선대학교",
    department: "직업치료학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 10,
    competitionRate: 6.7,
    cutoff50Grade: 5.35,
    cutoff70Grade: 5.27,
  },
  {
    university: "조선대학교",
    department: "직업치료학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 10.17,
    cutoff50Grade: 5.04,
    cutoff70Grade: 6.07,
  },
  {
    university: "조선대학교",
    department: "직업치료학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 22,
    competitionRate: 7.59,
    cutoff50Grade: 4.88,
    cutoff70Grade: 5.12,
  },
  // 건강기능공학과
  {
    university: "조선대학교",
    department: "건강기능공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 25,
    competitionRate: 4.16,
    cutoff50Grade: 4.51,
    cutoff70Grade: 4.48,
  },
  {
    university: "조선대학교",
    department: "건강기능공학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 6,
    competitionRate: 7.83,
    cutoff50Grade: 4.25,
    cutoff70Grade: 3.43,
  },
  {
    university: "조선대학교",
    department: "건강기능공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 41,
    competitionRate: 5.02,
    cutoff50Grade: 4.03,
    cutoff70Grade: 4.03,
  },
  // 철학전공 — Image 36
  {
    university: "조선대학교",
    department: "철학전공",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 5,
    competitionRate: 3.4,
    cutoff50Grade: 6.59,
    cutoff70Grade: 6.59,
  },
  {
    university: "조선대학교",
    department: "철학전공",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 3.86,
    cutoff50Grade: 5.77,
    cutoff70Grade: 7.15,
  },
  // 첨단에너지공학과
  {
    university: "조선대학교",
    department: "첨단에너지공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 16,
    competitionRate: 1.94,
    cutoff50Grade: 7.05,
    cutoff70Grade: 7.38,
  },
  {
    university: "조선대학교",
    department: "첨단에너지공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 4.1,
    cutoff50Grade: 6.75,
    cutoff70Grade: 7.09,
  },
  // 체육학과
  {
    university: "조선대학교",
    department: "체육학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 25,
    competitionRate: 4.2,
    cutoff50Grade: 2.44,
    cutoff70Grade: 4.02,
  },
  // 컴퓨터공학과
  {
    university: "조선대학교",
    department: "컴퓨터공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 12,
    competitionRate: 1.25,
    cutoff50Grade: 5.96,
    cutoff70Grade: 5.99,
  },
  {
    university: "조선대학교",
    department: "컴퓨터공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 17,
    competitionRate: 2.71,
    cutoff50Grade: 6.24,
    cutoff70Grade: 6.85,
  },
  // 태권도학과
  {
    university: "조선대학교",
    department: "태권도학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 14,
    competitionRate: 1.14,
    cutoff50Grade: 7.46,
    cutoff70Grade: 8.17,
  },
  // 토목공학과
  {
    university: "조선대학교",
    department: "토목공학과",
    admissionType: "학종",
    admissionName: "서류전형",
    quota: 11,
    competitionRate: 5.73,
    cutoff50Grade: 5.26,
    cutoff70Grade: 5,
  },
  {
    university: "조선대학교",
    department: "토목공학과",
    admissionType: "학종",
    admissionName: "면접전형",
    quota: 10,
    competitionRate: 10.6,
    cutoff50Grade: 5.73,
    cutoff70Grade: 5.92,
  },
  {
    university: "조선대학교",
    department: "토목공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 32,
    competitionRate: 6.16,
    cutoff50Grade: 4.78,
    cutoff70Grade: 5.06,
  },
];

for (const d of data) {
  console.log(`  {`);
  console.log(`    university: "${d.university}",`);
  console.log(`    department: "${d.department}",`);
  console.log(`    admissionType: "${d.admissionType}",`);
  console.log(`    admissionName: "${d.admissionName}",`);
  console.log(`    quota: ${d.quota},`);
  console.log(`    competitionRate: ${d.competitionRate},`);
  console.log(`    cutoff50Grade: ${d.cutoff50Grade},`);
  console.log(`    cutoff70Grade: ${d.cutoff70Grade},`);
  console.log(`  },`);
}
console.log(`\nTotal: ${data.length}`);
