// 공주대학교 커트라인 데이터 생성 스크립트
// 이미지에서 파싱한 데이터

interface Entry {
  university: string;
  department: string;
  admissionType: "교과" | "학종";
  admissionName: string;
  quota: number;
  competitionRate: number;
  cutoff50Grade: number;
  cutoff70Grade: number;
}

const data: Entry[] = [
  // 간호학과
  {
    university: "공주대학교",
    department: "간호학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 23,
    competitionRate: 8.3,
    cutoff50Grade: 3.19,
    cutoff70Grade: 3.27,
  },
  {
    university: "공주대학교",
    department: "간호학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 18,
    competitionRate: 8.4,
    cutoff50Grade: 3.53,
    cutoff70Grade: 3.61,
  },
  {
    university: "공주대학교",
    department: "간호학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 16,
    competitionRate: 24.3,
    cutoff50Grade: 3.29,
    cutoff70Grade: 3.35,
  },
  // 자율전공학부(공주캠)
  {
    university: "공주대학교",
    department: "자율전공학부(공주캠)",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 58,
    competitionRate: 11.2,
    cutoff50Grade: 4.17,
    cutoff70Grade: 4.3,
  },
  // 자율전공학부(인문사회과학대학)
  {
    university: "공주대학교",
    department: "자율전공학부(인문사회과학대학)",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 50,
    competitionRate: 11.1,
    cutoff50Grade: 4.32,
    cutoff70Grade: 4.42,
  },
  // 자율전공학부(자연과학대학)
  {
    university: "공주대학교",
    department: "자율전공학부(자연과학대학)",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 33,
    competitionRate: 6.3,
    cutoff50Grade: 4.6,
    cutoff70Grade: 4.76,
  },
  // 자율전공학부(산업과학대학)
  {
    university: "공주대학교",
    department: "자율전공학부(산업과학대학)",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 60,
    competitionRate: 5.3,
    cutoff50Grade: 4.95,
    cutoff70Grade: 5.13,
  },
  // 자율전공학부(천안공과대학)
  {
    university: "공주대학교",
    department: "자율전공학부(천안공과대학)",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 136,
    competitionRate: 6.4,
    cutoff50Grade: 4.87,
    cutoff70Grade: 5.03,
  },
  // 경영·금융교육과
  {
    university: "공주대학교",
    department: "경영·금융교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 6.8,
    cutoff50Grade: 3.51,
    cutoff70Grade: 3.52,
  },
  {
    university: "공주대학교",
    department: "경영·금융교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 3,
    competitionRate: 5.3,
    cutoff50Grade: 3.8,
    cutoff70Grade: 3.96,
  },
  {
    university: "공주대학교",
    department: "경영·금융교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 3.9,
    cutoff50Grade: 3.88,
    cutoff70Grade: 3.99,
  },
  // 경영학과
  {
    university: "공주대학교",
    department: "경영학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 15.4,
    cutoff50Grade: 3.37,
    cutoff70Grade: 3.47,
  },
  {
    university: "공주대학교",
    department: "경영학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 10.0,
    cutoff50Grade: 3.94,
    cutoff70Grade: 3.97,
  },
  {
    university: "공주대학교",
    department: "경영학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 14,
    competitionRate: 12.3,
    cutoff50Grade: 3.99,
    cutoff70Grade: 4.1,
  },
  // 경제통상학부
  {
    university: "공주대학교",
    department: "경제통상학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 15,
    competitionRate: 13.7,
    cutoff50Grade: 4.09,
    cutoff70Grade: 4.15,
  },
  {
    university: "공주대학교",
    department: "경제통상학부",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 4,
    competitionRate: 9.8,
    cutoff50Grade: 4.18,
    cutoff70Grade: 4.25,
  },
  {
    university: "공주대학교",
    department: "경제통상학부",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 19,
    competitionRate: 8.3,
    cutoff50Grade: 4.49,
    cutoff70Grade: 4.55,
  },
  // 관광&영어통역융복합학과
  {
    university: "공주대학교",
    department: "관광&영어통역융복합학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 16.4,
    cutoff50Grade: 4.32,
    cutoff70Grade: 4.43,
  },
  {
    university: "공주대학교",
    department: "관광&영어통역융복합학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 3,
    competitionRate: 9.3,
    cutoff50Grade: 4.09,
    cutoff70Grade: 4.1,
  },
  {
    university: "공주대학교",
    department: "관광&영어통역융복합학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 7.1,
    cutoff50Grade: 4.91,
    cutoff70Grade: 5.06,
  },
  // 관광경영학과
  {
    university: "공주대학교",
    department: "관광경영학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 21.1,
    cutoff50Grade: 3.92,
    cutoff70Grade: 4.12,
  },
  {
    university: "공주대학교",
    department: "관광경영학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 3,
    competitionRate: 9.7,
    cutoff50Grade: 4.41,
    cutoff70Grade: 4.7,
  },
  {
    university: "공주대학교",
    department: "관광경영학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 8.5,
    cutoff50Grade: 4.45,
    cutoff70Grade: 4.47,
  },
  // 교육학과
  {
    university: "공주대학교",
    department: "교육학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 3,
    competitionRate: 11.0,
    cutoff50Grade: 3.05,
    cutoff70Grade: 3.07,
  },
  {
    university: "공주대학교",
    department: "교육학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 8.0,
    cutoff50Grade: 2.89,
    cutoff70Grade: 3.02,
  },
  {
    university: "공주대학교",
    department: "교육학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 7.7,
    cutoff50Grade: 3.23,
    cutoff70Grade: 3.26,
  },
  // 국어교육과
  {
    university: "공주대학교",
    department: "국어교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 12.6,
    cutoff50Grade: 2.55,
    cutoff70Grade: 2.65,
  },
  {
    university: "공주대학교",
    department: "국어교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 4,
    competitionRate: 7.5,
    cutoff50Grade: 2.76,
    cutoff70Grade: 2.82,
  },
  {
    university: "공주대학교",
    department: "국어교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 16,
    competitionRate: 8.8,
    cutoff50Grade: 3.07,
    cutoff70Grade: 3.27,
  },
  // 국제학부
  {
    university: "공주대학교",
    department: "국제학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 24.0,
    cutoff50Grade: 4.3,
    cutoff70Grade: 4.38,
  },
  {
    university: "공주대학교",
    department: "국제학부",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 8.5,
    cutoff50Grade: 5.35,
    cutoff70Grade: 5.37,
  },
  {
    university: "공주대학교",
    department: "국제학부",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 12,
    competitionRate: 7.3,
    cutoff50Grade: 4.68,
    cutoff70Grade: 4.9,
  },
  // 독어독문학과
  {
    university: "공주대학교",
    department: "독어독문학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 3,
    competitionRate: 11.7,
    cutoff50Grade: 4.46,
    cutoff70Grade: 4.47,
  },
  {
    university: "공주대학교",
    department: "독어독문학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 7.0,
    cutoff50Grade: 4.65,
    cutoff70Grade: 4.77,
  },
  {
    university: "공주대학교",
    department: "독어독문학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 12,
    competitionRate: 4.4,
    cutoff50Grade: 5.39,
    cutoff70Grade: 5.53,
  },
  // 문헌정보교육과
  {
    university: "공주대학교",
    department: "문헌정보교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 10.0,
    cutoff50Grade: 2.54,
    cutoff70Grade: 2.59,
  },
  {
    university: "공주대학교",
    department: "문헌정보교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 4,
    competitionRate: 4.8,
    cutoff50Grade: 3.15,
    cutoff70Grade: 3.28,
  },
  {
    university: "공주대학교",
    department: "문헌정보교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 10.7,
    cutoff50Grade: 2.71,
    cutoff70Grade: 2.87,
  },
  // 문화재보존과학과
  {
    university: "공주대학교",
    department: "문화재보존과학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 2,
    competitionRate: 9.0,
    cutoff50Grade: 3.72,
    cutoff70Grade: 3.74,
  },
  {
    university: "공주대학교",
    department: "문화재보존과학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 5.0,
    cutoff50Grade: 5.18,
    cutoff70Grade: 5.6,
  },
  {
    university: "공주대학교",
    department: "문화재보존과학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 8.4,
    cutoff50Grade: 4.06,
    cutoff70Grade: 4.09,
  },
  // 법학과
  {
    university: "공주대학교",
    department: "법학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 14.4,
    cutoff50Grade: 3.84,
    cutoff70Grade: 3.88,
  },
  {
    university: "공주대학교",
    department: "법학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 6.5,
    cutoff50Grade: 4.71,
    cutoff70Grade: 4.77,
  },
  {
    university: "공주대학교",
    department: "법학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 8.8,
    cutoff50Grade: 3.5,
    cutoff70Grade: 3.77,
  },
  // 보건행정학과
  {
    university: "공주대학교",
    department: "보건행정학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 7.8,
    cutoff50Grade: 4.07,
    cutoff70Grade: 4.09,
  },
  {
    university: "공주대학교",
    department: "보건행정학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 8,
    competitionRate: 4.1,
    cutoff50Grade: 4.39,
    cutoff70Grade: 4.95,
  },
  {
    university: "공주대학교",
    department: "보건행정학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 12,
    competitionRate: 9.4,
    cutoff50Grade: 4.36,
    cutoff70Grade: 4.54,
  },
  // 부동산학과
  {
    university: "공주대학교",
    department: "부동산학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 8.2,
    cutoff50Grade: 5.26,
    cutoff70Grade: 5.41,
  },
  {
    university: "공주대학교",
    department: "부동산학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 4,
    competitionRate: 6.5,
    cutoff50Grade: 6.35,
    cutoff70Grade: 6.36,
  },
  // 불어불문학과
  {
    university: "공주대학교",
    department: "불어불문학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 13.3,
    cutoff50Grade: 4.34,
    cutoff70Grade: 4.36,
  },
  {
    university: "공주대학교",
    department: "불어불문학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 9.5,
    cutoff50Grade: 4.9,
    cutoff70Grade: 5.03,
  },
  {
    university: "공주대학교",
    department: "불어불문학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 4.0,
    cutoff50Grade: 5.42,
    cutoff70Grade: 5.51,
  },
  // 사학과
  {
    university: "공주대학교",
    department: "사학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 13.2,
    cutoff50Grade: 3.72,
    cutoff70Grade: 3.78,
  },
  {
    university: "공주대학교",
    department: "사학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 9.5,
    cutoff50Grade: 4.4,
    cutoff70Grade: 4.4,
  },
  {
    university: "공주대학교",
    department: "사학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 16.9,
    cutoff50Grade: 3.9,
    cutoff70Grade: 3.92,
  },
  // 사회복지학과
  {
    university: "공주대학교",
    department: "사회복지학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 14.8,
    cutoff50Grade: 3.88,
    cutoff70Grade: 3.93,
  },
  {
    university: "공주대학교",
    department: "사회복지학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 7.5,
    cutoff50Grade: 4.08,
    cutoff70Grade: 4.09,
  },
  {
    university: "공주대학교",
    department: "사회복지학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 18.8,
    cutoff50Grade: 4.24,
    cutoff70Grade: 4.43,
  },
  // 역사교육과
  {
    university: "공주대학교",
    department: "역사교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 4,
    competitionRate: 9.8,
    cutoff50Grade: 2.17,
    cutoff70Grade: 2.4,
  },
  {
    university: "공주대학교",
    department: "역사교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 6.0,
    cutoff50Grade: 2.83,
    cutoff70Grade: 2.99,
  },
  {
    university: "공주대학교",
    department: "역사교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 9.0,
    cutoff50Grade: 2.66,
    cutoff70Grade: 2.75,
  },
  // 영어교육과
  {
    university: "공주대학교",
    department: "영어교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 8.3,
    cutoff50Grade: 2.8,
    cutoff70Grade: 2.89,
  },
  {
    university: "공주대학교",
    department: "영어교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 6,
    competitionRate: 5.8,
    cutoff50Grade: 2.88,
    cutoff70Grade: 3.04,
  },
  {
    university: "공주대학교",
    department: "영어교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 16,
    competitionRate: 11.7,
    cutoff50Grade: 3.39,
    cutoff70Grade: 3.55,
  },
  // 영어영문학과
  {
    university: "공주대학교",
    department: "영어영문학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 15.0,
    cutoff50Grade: 4.01,
    cutoff70Grade: 4.08,
  },
  {
    university: "공주대학교",
    department: "영어영문학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 9.5,
    cutoff50Grade: 4.45,
    cutoff70Grade: 4.48,
  },
  {
    university: "공주대학교",
    department: "영어영문학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 16,
    competitionRate: 8.3,
    cutoff50Grade: 4.48,
    cutoff70Grade: 4.8,
  },
  // 외식상품학과
  {
    university: "공주대학교",
    department: "외식상품학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 3,
    competitionRate: 5.0,
    cutoff50Grade: 4.03,
    cutoff70Grade: 4.85,
  },
  {
    university: "공주대학교",
    department: "외식상품학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 5.3,
    cutoff50Grade: 5.53,
    cutoff70Grade: 5.83,
  },
  // 유아교육과
  {
    university: "공주대학교",
    department: "유아교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 8.3,
    cutoff50Grade: 4.79,
    cutoff70Grade: 5.08,
  },
  {
    university: "공주대학교",
    department: "유아교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 5,
    competitionRate: 6.8,
    cutoff50Grade: 3.76,
    cutoff70Grade: 3.92,
  },
  {
    university: "공주대학교",
    department: "유아교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 16,
    competitionRate: 8.1,
    cutoff50Grade: 3.51,
    cutoff70Grade: 3.7,
  },
  // 윤리교육과
  {
    university: "공주대학교",
    department: "윤리교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 3,
    competitionRate: 22.3,
    cutoff50Grade: 2.58,
    cutoff70Grade: 2.61,
  },
  {
    university: "공주대학교",
    department: "윤리교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 8.0,
    cutoff50Grade: 2.96,
    cutoff70Grade: 3.05,
  },
  {
    university: "공주대학교",
    department: "윤리교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 10.1,
    cutoff50Grade: 3.03,
    cutoff70Grade: 3.27,
  },
  // 의류상품학과
  {
    university: "공주대학교",
    department: "의류상품학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 2,
    competitionRate: 11.0,
    cutoff50Grade: 3.39,
    cutoff70Grade: 3.48,
  },
  {
    university: "공주대학교",
    department: "의류상품학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 5.0,
    cutoff50Grade: 4.31,
    cutoff70Grade: 4.51,
  },
  {
    university: "공주대학교",
    department: "의류상품학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 11.7,
    cutoff50Grade: 4.42,
    cutoff70Grade: 4.55,
  },
  // 일반사회교육과
  {
    university: "공주대학교",
    department: "일반사회교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 4,
    competitionRate: 8.5,
    cutoff50Grade: 2.25,
    cutoff70Grade: 2.39,
  },
  {
    university: "공주대학교",
    department: "일반사회교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 6.0,
    cutoff50Grade: 2.95,
    cutoff70Grade: 3.02,
  },
  {
    university: "공주대학교",
    department: "일반사회교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 12,
    competitionRate: 6.3,
    cutoff50Grade: 2.79,
    cutoff70Grade: 2.93,
  },
  // 중어중문학과
  {
    university: "공주대학교",
    department: "중어중문학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 15.8,
    cutoff50Grade: 4.3,
    cutoff70Grade: 4.39,
  },
  {
    university: "공주대학교",
    department: "중어중문학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 3,
    competitionRate: 10.3,
    cutoff50Grade: 4.43,
    cutoff70Grade: 4.43,
  },
  {
    university: "공주대학교",
    department: "중어중문학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 15,
    competitionRate: 5.6,
    cutoff50Grade: 4.96,
    cutoff70Grade: 5.24,
  },
  // 지리교육과
  {
    university: "공주대학교",
    department: "지리교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 18.2,
    cutoff50Grade: 2.83,
    cutoff70Grade: 2.83,
  },
  {
    university: "공주대학교",
    department: "지리교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 6.0,
    cutoff50Grade: 3.59,
    cutoff70Grade: 3.7,
  },
  {
    university: "공주대학교",
    department: "지리교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 8.4,
    cutoff50Grade: 3.27,
    cutoff70Grade: 3.36,
  },
  // 지리학과
  {
    university: "공주대학교",
    department: "지리학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 11.0,
    cutoff50Grade: 3.88,
    cutoff70Grade: 3.97,
  },
  {
    university: "공주대학교",
    department: "지리학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 6.0,
    cutoff50Grade: 4.25,
    cutoff70Grade: 4.25,
  },
  {
    university: "공주대학교",
    department: "지리학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 8.9,
    cutoff50Grade: 4.56,
    cutoff70Grade: 4.59,
  },
  // 지역사회개발학과
  {
    university: "공주대학교",
    department: "지역사회개발학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 4,
    competitionRate: 6.5,
    cutoff50Grade: 5.21,
    cutoff70Grade: 5.3,
  },
  {
    university: "공주대학교",
    department: "지역사회개발학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 3,
    competitionRate: 4.0,
    cutoff50Grade: 5.73,
    cutoff70Grade: 5.92,
  },
  // 특수교육과
  {
    university: "공주대학교",
    department: "특수교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 15,
    competitionRate: 9.6,
    cutoff50Grade: 3.75,
    cutoff70Grade: 3.94,
  },
  {
    university: "공주대학교",
    department: "특수교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 10,
    competitionRate: 5.0,
    cutoff50Grade: 4.29,
    cutoff70Grade: 4.39,
  },
  {
    university: "공주대학교",
    department: "특수교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 20,
    competitionRate: 5.9,
    cutoff50Grade: 4.0,
    cutoff70Grade: 4.22,
  },
  // 한문교육과
  {
    university: "공주대학교",
    department: "한문교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 6.6,
    cutoff50Grade: 3.31,
    cutoff70Grade: 3.34,
  },
  {
    university: "공주대학교",
    department: "한문교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 4,
    competitionRate: 5.0,
    cutoff50Grade: 4.08,
    cutoff70Grade: 4.3,
  },
  {
    university: "공주대학교",
    department: "한문교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 5.6,
    cutoff50Grade: 3.71,
    cutoff70Grade: 3.83,
  },
  // 행정학과
  {
    university: "공주대학교",
    department: "행정학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 13.3,
    cutoff50Grade: 3.83,
    cutoff70Grade: 3.91,
  },
  {
    university: "공주대학교",
    department: "행정학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 3,
    competitionRate: 9.0,
    cutoff50Grade: 3.91,
    cutoff70Grade: 3.95,
  },
  {
    university: "공주대학교",
    department: "행정학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 8.8,
    cutoff50Grade: 4.0,
    cutoff70Grade: 4.08,
  },
  // === 자연/공학 ===
  // 건축학과
  {
    university: "공주대학교",
    department: "건축학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 3,
    competitionRate: 15.0,
    cutoff50Grade: 3.68,
    cutoff70Grade: 3.7,
  },
  {
    university: "공주대학교",
    department: "건축학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 6.5,
    cutoff50Grade: 4.36,
    cutoff70Grade: 4.45,
  },
  {
    university: "공주대학교",
    department: "건축학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 13.7,
    cutoff50Grade: 4.03,
    cutoff70Grade: 4.16,
  },
  // 광학과
  {
    university: "공주대학교",
    department: "광학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 5.5,
    cutoff50Grade: 5.67,
    cutoff70Grade: 5.81,
  },
  {
    university: "공주대학교",
    department: "광학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 5.0,
    cutoff50Grade: 5.69,
    cutoff70Grade: 6.11,
  },
  // 그린스마트건축공학과
  {
    university: "공주대학교",
    department: "그린스마트건축공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 12,
    competitionRate: 9.2,
    cutoff50Grade: 4.56,
    cutoff70Grade: 4.6,
  },
  {
    university: "공주대학교",
    department: "그린스마트건축공학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 6,
    competitionRate: 8.3,
    cutoff50Grade: 4.65,
    cutoff70Grade: 4.8,
  },
  {
    university: "공주대학교",
    department: "그린스마트건축공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 1,
    competitionRate: 9.0,
    cutoff50Grade: 4.92,
    cutoff70Grade: 4.92,
  },
  // 기계자동차공학부
  {
    university: "공주대학교",
    department: "기계자동차공학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 40,
    competitionRate: 9.2,
    cutoff50Grade: 4.74,
    cutoff70Grade: 4.8,
  },
  {
    university: "공주대학교",
    department: "기계자동차공학부",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 30,
    competitionRate: 7.3,
    cutoff50Grade: 4.83,
    cutoff70Grade: 5.0,
  },
  // 기술·가정교육과
  {
    university: "공주대학교",
    department: "기술·가정교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 4,
    competitionRate: 7.0,
    cutoff50Grade: 2.96,
    cutoff70Grade: 3.16,
  },
  {
    university: "공주대학교",
    department: "기술·가정교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 4.5,
    cutoff50Grade: 4.14,
    cutoff70Grade: 4.14,
  },
  {
    university: "공주대학교",
    department: "기술·가정교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 7.3,
    cutoff50Grade: 3.52,
    cutoff70Grade: 3.56,
  },
  // 대기과학과
  {
    university: "공주대학교",
    department: "대기과학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 9.3,
    cutoff50Grade: 4.01,
    cutoff70Grade: 4.09,
  },
  {
    university: "공주대학교",
    department: "대기과학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 1,
    competitionRate: 5.0,
    cutoff50Grade: 5.06,
    cutoff70Grade: 5.06,
  },
  {
    university: "공주대학교",
    department: "대기과학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 12,
    competitionRate: 7.9,
    cutoff50Grade: 4.13,
    cutoff70Grade: 4.55,
  },
  // 데이터정보물리학과
  {
    university: "공주대학교",
    department: "데이터정보물리학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 7.1,
    cutoff50Grade: 4.75,
    cutoff70Grade: 4.95,
  },
  {
    university: "공주대학교",
    department: "데이터정보물리학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 3,
    competitionRate: 5.7,
    cutoff50Grade: 5.2,
    cutoff70Grade: 5.25,
  },
  {
    university: "공주대학교",
    department: "데이터정보물리학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 3.9,
    cutoff50Grade: 5.34,
    cutoff70Grade: 5.7,
  },
  // 도시·교통공학과
  {
    university: "공주대학교",
    department: "도시·교통공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 10.4,
    cutoff50Grade: 4.65,
    cutoff70Grade: 4.72,
  },
  {
    university: "공주대학교",
    department: "도시·교통공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 8.0,
    cutoff50Grade: 4.84,
    cutoff70Grade: 4.88,
  },
  // 동물자원학과
  {
    university: "공주대학교",
    department: "동물자원학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 15.6,
    cutoff50Grade: 3.81,
    cutoff70Grade: 4.28,
  },
  {
    university: "공주대학교",
    department: "동물자원학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 3.0,
    cutoff50Grade: 5.57,
    cutoff70Grade: 5.67,
  },
  {
    university: "공주대학교",
    department: "동물자원학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 16.9,
    cutoff50Grade: 5.14,
    cutoff70Grade: 5.21,
  },
  // 디지털융합금형공학과
  {
    university: "공주대학교",
    department: "디지털융합금형공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 12.0,
    cutoff50Grade: 5.83,
    cutoff70Grade: 5.93,
  },
  {
    university: "공주대학교",
    department: "디지털융합금형공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 4,
    competitionRate: 7.0,
    cutoff50Grade: 5.28,
    cutoff70Grade: 5.67,
  },
  // 물리교육과
  {
    university: "공주대학교",
    department: "물리교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 2,
    competitionRate: 5.0,
    cutoff50Grade: 3.89,
    cutoff70Grade: 4.09,
  },
  {
    university: "공주대학교",
    department: "물리교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 4.0,
    cutoff50Grade: 3.5,
    cutoff70Grade: 3.81,
  },
  {
    university: "공주대학교",
    department: "물리교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 14,
    competitionRate: 3.1,
    cutoff50Grade: 3.64,
    cutoff70Grade: 3.85,
  },
  // 미래자동차공학과
  {
    university: "공주대학교",
    department: "미래자동차공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 5.8,
    cutoff50Grade: 5.23,
    cutoff70Grade: 5.3,
  },
  {
    university: "공주대학교",
    department: "미래자동차공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 7.0,
    cutoff50Grade: 5.74,
    cutoff70Grade: 5.78,
  },
  // 산림과학과
  {
    university: "공주대학교",
    department: "산림과학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 9.3,
    cutoff50Grade: 4.54,
    cutoff70Grade: 4.6,
  },
  {
    university: "공주대학교",
    department: "산림과학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 5.9,
    cutoff50Grade: 4.57,
    cutoff70Grade: 4.75,
  },
  // 산업공학과
  {
    university: "공주대학교",
    department: "산업공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 9.9,
    cutoff50Grade: 5.02,
    cutoff70Grade: 5.18,
  },
  {
    university: "공주대학교",
    department: "산업공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 4.4,
    cutoff50Grade: 6.0,
    cutoff70Grade: 6.0,
  },
  // 산업유통학과
  {
    university: "공주대학교",
    department: "산업유통학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 3,
    competitionRate: 5.7,
    cutoff50Grade: 5.49,
    cutoff70Grade: 5.8,
  },
  {
    university: "공주대학교",
    department: "산업유통학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 4,
    competitionRate: 4.3,
    cutoff50Grade: 6.19,
    cutoff70Grade: 6.27,
  },
  // 생명과학과
  {
    university: "공주대학교",
    department: "생명과학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 11.0,
    cutoff50Grade: 3.7,
    cutoff70Grade: 3.82,
  },
  {
    university: "공주대학교",
    department: "생명과학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 3,
    competitionRate: 5.3,
    cutoff50Grade: 3.58,
    cutoff70Grade: 3.73,
  },
  {
    university: "공주대학교",
    department: "생명과학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 17,
    competitionRate: 11.5,
    cutoff50Grade: 4.81,
    cutoff70Grade: 4.94,
  },
  // 생물교육과
  {
    university: "공주대학교",
    department: "생물교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 4,
    competitionRate: 6.3,
    cutoff50Grade: 3.43,
    cutoff70Grade: 3.68,
  },
  {
    university: "공주대학교",
    department: "생물교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 4.5,
    cutoff50Grade: 2.74,
    cutoff70Grade: 2.74,
  },
  {
    university: "공주대학교",
    department: "생물교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 7.7,
    cutoff50Grade: 2.97,
    cutoff70Grade: 3.09,
  },
  // 소프트웨어학과
  {
    university: "공주대학교",
    department: "소프트웨어학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 16,
    competitionRate: 5.7,
    cutoff50Grade: 4.14,
    cutoff70Grade: 4.31,
  },
  {
    university: "공주대학교",
    department: "소프트웨어학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 3,
    competitionRate: 5.0,
    cutoff50Grade: 4.52,
    cutoff70Grade: 4.56,
  },
  {
    university: "공주대학교",
    department: "소프트웨어학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 9.9,
    cutoff50Grade: 4.45,
    cutoff70Grade: 4.58,
  },
  // 수산생명의학과
  {
    university: "공주대학교",
    department: "수산생명의학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 10.0,
    cutoff50Grade: 5.51,
    cutoff70Grade: 5.61,
  },
  {
    university: "공주대학교",
    department: "수산생명의학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 9.6,
    cutoff50Grade: 5.31,
    cutoff70Grade: 5.53,
  },
  // 수학교육과
  {
    university: "공주대학교",
    department: "수학교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 13.6,
    cutoff50Grade: 2.75,
    cutoff70Grade: 2.77,
  },
  {
    university: "공주대학교",
    department: "수학교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 4,
    competitionRate: 6.3,
    cutoff50Grade: 2.74,
    cutoff70Grade: 2.75,
  },
  {
    university: "공주대학교",
    department: "수학교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 16,
    competitionRate: 6.5,
    cutoff50Grade: 3.02,
    cutoff70Grade: 3.3,
  },
  // 스마트인프라공학과
  {
    university: "공주대학교",
    department: "스마트인프라공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 21,
    competitionRate: 6.5,
    cutoff50Grade: 5.19,
    cutoff70Grade: 5.36,
  },
  {
    university: "공주대학교",
    department: "스마트인프라공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 5.8,
    cutoff50Grade: 5.41,
    cutoff70Grade: 5.5,
  },
  // 스마트정보기술공학과
  {
    university: "공주대학교",
    department: "스마트정보기술공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 5.9,
    cutoff50Grade: 4.65,
    cutoff70Grade: 4.7,
  },
  {
    university: "공주대학교",
    department: "스마트정보기술공학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 4.5,
    cutoff50Grade: 6.22,
    cutoff70Grade: 6.29,
  },
  {
    university: "공주대학교",
    department: "스마트정보기술공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 5.8,
    cutoff50Grade: 4.88,
    cutoff70Grade: 4.91,
  },
  // 스마트팜공학과
  {
    university: "공주대학교",
    department: "스마트팜공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 9.7,
    cutoff50Grade: 4.52,
    cutoff70Grade: 4.81,
  },
  {
    university: "공주대학교",
    department: "스마트팜공학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 3.5,
    cutoff50Grade: 5.66,
    cutoff70Grade: 5.76,
  },
  {
    university: "공주대학교",
    department: "스마트팜공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 10.5,
    cutoff50Grade: 5.14,
    cutoff70Grade: 5.51,
  },
  // 식물자원학과
  {
    university: "공주대학교",
    department: "식물자원학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 6.5,
    cutoff50Grade: 4.71,
    cutoff70Grade: 4.74,
  },
  {
    university: "공주대학교",
    department: "식물자원학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 5.8,
    cutoff50Grade: 5.11,
    cutoff70Grade: 5.21,
  },
  // 식품공학과
  {
    university: "공주대학교",
    department: "식품공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 8.0,
    cutoff50Grade: 3.46,
    cutoff70Grade: 4.3,
  },
  {
    university: "공주대학교",
    department: "식품공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 10.2,
    cutoff50Grade: 4.33,
    cutoff70Grade: 4.39,
  },
  // 식품영양학과
  {
    university: "공주대학교",
    department: "식품영양학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 13.0,
    cutoff50Grade: 4.05,
    cutoff70Grade: 4.11,
  },
  {
    university: "공주대학교",
    department: "식품영양학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 5.0,
    cutoff50Grade: 5.62,
    cutoff70Grade: 5.63,
  },
  {
    university: "공주대학교",
    department: "식품영양학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 11.7,
    cutoff50Grade: 4.77,
    cutoff70Grade: 4.9,
  },
  // 신소재공학부
  {
    university: "공주대학교",
    department: "신소재공학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 20,
    competitionRate: 6.4,
    cutoff50Grade: 4.34,
    cutoff70Grade: 4.4,
  },
  {
    university: "공주대학교",
    department: "신소재공학부",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 23,
    competitionRate: 5.5,
    cutoff50Grade: 4.58,
    cutoff70Grade: 4.77,
  },
  // 원예학과
  {
    university: "공주대학교",
    department: "원예학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 12.7,
    cutoff50Grade: 4.66,
    cutoff70Grade: 4.85,
  },
  {
    university: "공주대학교",
    department: "원예학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 7.9,
    cutoff50Grade: 4.17,
    cutoff70Grade: 4.77,
  },
  // 응급구조학과
  {
    university: "공주대학교",
    department: "응급구조학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 14.8,
    cutoff50Grade: 3.72,
    cutoff70Grade: 3.8,
  },
  {
    university: "공주대학교",
    department: "응급구조학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 4,
    competitionRate: 7.5,
    cutoff50Grade: 4.09,
    cutoff70Grade: 4.17,
  },
  {
    university: "공주대학교",
    department: "응급구조학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 17.4,
    cutoff50Grade: 4.06,
    cutoff70Grade: 4.24,
  },
  // 응용수학과
  {
    university: "공주대학교",
    department: "응용수학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 7.6,
    cutoff50Grade: 4.54,
    cutoff70Grade: 4.63,
  },
  {
    university: "공주대학교",
    department: "응용수학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 5.5,
    cutoff50Grade: 5.21,
    cutoff70Grade: 5.3,
  },
  {
    university: "공주대학교",
    department: "응용수학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 12,
    competitionRate: 4.1,
    cutoff50Grade: 5.18,
    cutoff70Grade: 5.32,
  },
  // 의료정보학과
  {
    university: "공주대학교",
    department: "의료정보학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 9.4,
    cutoff50Grade: 4.59,
    cutoff70Grade: 4.62,
  },
  {
    university: "공주대학교",
    department: "의료정보학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 7,
    competitionRate: 7.9,
    cutoff50Grade: 4.49,
    cutoff70Grade: 4.53,
  },
  {
    university: "공주대학교",
    department: "의료정보학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 7.3,
    cutoff50Grade: 5.22,
    cutoff70Grade: 5.41,
  },
  // 인공지능학부
  {
    university: "공주대학교",
    department: "인공지능학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 15,
    competitionRate: 5.3,
    cutoff50Grade: 4.34,
    cutoff70Grade: 4.36,
  },
  {
    university: "공주대학교",
    department: "인공지능학부",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 6.3,
    cutoff50Grade: 4.68,
    cutoff70Grade: 4.78,
  },
  // 전기전자제어공학부
  {
    university: "공주대학교",
    department: "전기전자제어공학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 71,
    competitionRate: 8.5,
    cutoff50Grade: 4.53,
    cutoff70Grade: 4.65,
  },
  {
    university: "공주대학교",
    department: "전기전자제어공학부",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 16,
    competitionRate: 8.4,
    cutoff50Grade: 4.36,
    cutoff70Grade: 4.64,
  },
  // 정보통신공학과
  {
    university: "공주대학교",
    department: "정보통신공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 10.8,
    cutoff50Grade: 4.73,
    cutoff70Grade: 4.91,
  },
  {
    university: "공주대학교",
    department: "정보통신공학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 8.0,
    cutoff50Grade: 4.68,
    cutoff70Grade: 4.77,
  },
  {
    university: "공주대학교",
    department: "정보통신공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 5.9,
    cutoff50Grade: 4.91,
    cutoff70Grade: 5.16,
  },
  // 조경학과
  {
    university: "공주대학교",
    department: "조경학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 8.8,
    cutoff50Grade: 5.11,
    cutoff70Grade: 5.42,
  },
  {
    university: "공주대학교",
    department: "조경학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 9.0,
    cutoff50Grade: 5.61,
    cutoff70Grade: 5.68,
  },
  // 지구과학교육과
  {
    university: "공주대학교",
    department: "지구과학교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 4,
    competitionRate: 6.0,
    cutoff50Grade: 3.22,
    cutoff70Grade: 3.67,
  },
  {
    university: "공주대학교",
    department: "지구과학교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 4.0,
    cutoff50Grade: 4.68,
    cutoff70Grade: 4.73,
  },
  {
    university: "공주대학교",
    department: "지구과학교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 6.3,
    cutoff50Grade: 2.87,
    cutoff70Grade: 2.98,
  },
  // 지능형모빌리티공학과
  {
    university: "공주대학교",
    department: "지능형모빌리티공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 6.5,
    cutoff50Grade: 5.24,
    cutoff70Grade: 5.28,
  },
  {
    university: "공주대학교",
    department: "지능형모빌리티공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 5,
    competitionRate: 5.4,
    cutoff50Grade: 5.18,
    cutoff70Grade: 5.29,
  },
  // 지역건설공학과
  {
    university: "공주대학교",
    department: "지역건설공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 3.7,
    cutoff50Grade: 6.06,
    cutoff70Grade: 6.68,
  },
  // 지질환경과학과
  {
    university: "공주대학교",
    department: "지질환경과학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 11,
    competitionRate: 7.2,
    cutoff50Grade: 4.62,
    cutoff70Grade: 4.68,
  },
  {
    university: "공주대학교",
    department: "지질환경과학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 3,
    competitionRate: 4.7,
    cutoff50Grade: 4.92,
    cutoff70Grade: 5.29,
  },
  {
    university: "공주대학교",
    department: "지질환경과학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 7.3,
    cutoff50Grade: 5.22,
    cutoff70Grade: 5.41,
  },
  // 컴퓨터공학과
  {
    university: "공주대학교",
    department: "컴퓨터공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 19,
    competitionRate: 8.6,
    cutoff50Grade: 4.01,
    cutoff70Grade: 4.16,
  },
  {
    university: "공주대학교",
    department: "컴퓨터공학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 3,
    competitionRate: 4.7,
    cutoff50Grade: 4.12,
    cutoff70Grade: 4.19,
  },
  {
    university: "공주대학교",
    department: "컴퓨터공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 12.4,
    cutoff50Grade: 4.21,
    cutoff70Grade: 4.28,
  },
  // 컴퓨터교육과
  {
    university: "공주대학교",
    department: "컴퓨터교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 6.8,
    cutoff50Grade: 3.26,
    cutoff70Grade: 3.3,
  },
  {
    university: "공주대학교",
    department: "컴퓨터교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 3,
    competitionRate: 4.3,
    cutoff50Grade: 3.86,
    cutoff70Grade: 4.68,
  },
  {
    university: "공주대학교",
    department: "컴퓨터교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 8.0,
    cutoff50Grade: 3.86,
    cutoff70Grade: 4.11,
  },
  // 특수동물학과
  {
    university: "공주대학교",
    department: "특수동물학과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 9.0,
    cutoff50Grade: 3.73,
    cutoff70Grade: 3.81,
  },
  {
    university: "공주대학교",
    department: "특수동물학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 25.1,
    cutoff50Grade: 3.42,
    cutoff70Grade: 3.5,
  },
  // 화학공학부
  {
    university: "공주대학교",
    department: "화학공학부",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 17,
    competitionRate: 7.6,
    cutoff50Grade: 4.11,
    cutoff70Grade: 4.17,
  },
  {
    university: "공주대학교",
    department: "화학공학부",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 5.9,
    cutoff50Grade: 4.38,
    cutoff70Grade: 4.64,
  },
  // 화학과
  {
    university: "공주대학교",
    department: "화학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 14,
    competitionRate: 8.5,
    cutoff50Grade: 4.32,
    cutoff70Grade: 4.36,
  },
  {
    university: "공주대학교",
    department: "화학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 7,
    competitionRate: 7.4,
    cutoff50Grade: 4.34,
    cutoff70Grade: 4.45,
  },
  // 화학교육과
  {
    university: "공주대학교",
    department: "화학교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 3,
    competitionRate: 6.7,
    cutoff50Grade: 3.57,
    cutoff70Grade: 3.65,
  },
  {
    university: "공주대학교",
    department: "화학교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 2,
    competitionRate: 4.0,
    cutoff50Grade: 3.03,
    cutoff70Grade: 3.03,
  },
  {
    university: "공주대학교",
    department: "화학교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 10,
    competitionRate: 4.7,
    cutoff50Grade: 3.34,
    cutoff70Grade: 3.73,
  },
  // 환경공학과
  {
    university: "공주대학교",
    department: "환경공학과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 8,
    competitionRate: 7.6,
    cutoff50Grade: 4.46,
    cutoff70Grade: 4.61,
  },
  {
    university: "공주대학교",
    department: "환경공학과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 9,
    competitionRate: 8.9,
    cutoff50Grade: 4.7,
    cutoff70Grade: 4.74,
  },
  // 환경교육과
  {
    university: "공주대학교",
    department: "환경교육과",
    admissionType: "교과",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 6.3,
    cutoff50Grade: 3.62,
    cutoff70Grade: 3.74,
  },
  {
    university: "공주대학교",
    department: "환경교육과",
    admissionType: "교과",
    admissionName: "지역인재",
    quota: 4,
    competitionRate: 4.3,
    cutoff50Grade: 3.22,
    cutoff70Grade: 3.92,
  },
  {
    university: "공주대학교",
    department: "환경교육과",
    admissionType: "학종",
    admissionName: "일반전형",
    quota: 6,
    competitionRate: 4.2,
    cutoff50Grade: 3.89,
    cutoff70Grade: 4.14,
  },
];

// 출력: admission-cutoff-data.ts에 붙여넣을 형식
for (const d of data) {
  console.log(`  {`);
  console.log(`    university: "${d.university}",`);
  console.log(`    department: "${d.department}",`);
  console.log(`    admissionType: "${d.admissionType}",`);
  console.log(`    admissionName: "${d.admissionName}",`);
  console.log(`    quota: ${d.quota},`);
  console.log(`    competitionRate: ${d.competitionRate},`);
  console.log(`    cutoff50Grade: ${d.cutoff50Grade},`);
  console.log(`    cutoff70Grade: ${d.cutoff70Grade},`);
  console.log(`  },`);
}

console.log(`\nTotal entries: ${data.length}`);
